name: Node.js CI/CD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Test AWS
        run: aws --version
      - name: Setting up AWS credentials
        run: export AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}} AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}} AWS_DEFAULT_REGION=us-east-1
      - name: Show credentials
        run: echo $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY
      - name: List buckets
        run: aws s3 ls
      # - uses: actions/checkout@v2
      # - name: Use Node.js ${{ matrix.node-version }}
        # uses: actions/setup-node@v2
        # with:
          # node-version: ${{ matrix.node-version }}
      # - run: yarn test
      # - run: echo "event_name - ${{ github.event_name }}"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "github-actions-w11"
          heroku_email: "joshua.navarro35@gmail.com"
